### ISSUE TITLE
receive_request got called but client side still timeouts

### ISSUE THREAD

**Issue by jackalcooper** [balena/elixir-sippet#1]
Hello hello. First, thanks for implementing this! 

I added config Sippet.Core and the receive_request callback got called but the client still timeouts. It is the Telephone macOS client. Could you give me some hint on what to do next?

Thank you!

**Comment by jackalcooper** [comment]
![image](https://user-images.githubusercontent.com/5133557/27275107-95f70702-5508-11e7-84b1-749515d03d70.png)

**Comment by balena** [comment]
Hello @jackalcooper.

Some questions:
* Have you generated a REGISTER response for your app and passed it back to `Sippet.Transactions`?
* I didn't provide a Digest authentication function, how are you authenticating the application?
* Another possibility is that the app is not accepting the response because it is considered invalid, can you check this?

If you share some code maybe I could provide better answers to your case.

**Comment by jackalcooper** [comment]
Thanks for your hints. It connects now!

The code is fairly simple actually. I didn't find `Sippet.Message.to_response/2` and tried to build a request by myself and it fails.
```elixir
    def receive_request(incoming_request, server_key) do
        outgoing_response = incoming_request |> Sippet.Message.to_response(200)
        Transactions.send_response(outgoing_response, server_key)
    end
```

I have one question. Why do we need to imperatively call `send_response/2`? Idiomatically a call back returns `{:ok, response}` or `{:error, reason}`.

**Comment by balena** [comment]
> Why do we need to imperatively call send_response/2?
Because you may need to wait for some other event to happen before answer the request. Your test code fits the case where a SIP response would come in the form of a return value, but there are several cases where this approach don't fit well. For instance, the core of a proxy I have implemented using `Sippet` maintains a `Registry` of client and server transactions, so child processes can accumulate requests/responses from different transactions in order to do their job, like handling CANCEL for a previously forwarded INVITE, handling multiple responses for a forked forward, etc.

> Idiomatically a callback in Erlang or Elixir returns things like `{:resp, resp}`, `{:ok, response}` or `{:error, reason}`.
Actually the `Sippet.Core` is a protocol where `receive_request/2`, `receive_response/2` and `receive_error/2` can return `any` term; that means the return value is simply ignored.

**Comment by balena** [comment]
I think this case is now closed.
