### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by martinos** [balena/elixir-sippet#26]
I see an constant increase of memory when running an app. 

I have noticed that the sippet supervisor consumes more and more memory. 

```
iex(as@stirsrv01)1> Supervisor.count_children(:as_stack_sup)
%{active: 47, specs: 173756, supervisors: 1, workers: 173755}
```

I think that the application uses a simple Supervisor and not a DynamicSupervisor. 

This is very easy to reproduce, just let the application run while sending calls to it then call the `Supervisor.count_children()` function.

**Comment by balena** [comment]
While I understand the problem you're referring to, I don't see how/why moving from Supervisor to DynamicSupervisor would fix it.

So, transactions are short living processes. They are started on demand and after every timer ends, they stop. In order to stop properly they should finish with reason :normal.

However the :restart flag should be set to :transient. I'm using GenStateMachine, which doesn't provide the option to set such at the "use GenStateMachine" declaration.

So it should be part of the child_spec function. If you inspect Sippet.Transactions.Client.child_spec, you'll notice the flag being set there as :transient as expected.

**Comment by balena** [comment]
Oh, maybe I got it now. So when child process stop, their supervisors maintain their `child_spec/1` in memory case you want to restart them. And in this case the code leaks memory, isn't it?

**Comment by martinos** [comment]
Exactly, I should have been more precise.  DynamicSupervisor takes care of cleaning up of dead process's child_spec.

**Comment by balena** [comment]
@martinos, added some other modifications and fixed the unit tests: https://github.com/balena/elixir-sippet/pull/29.

Merged. Thanks!
